# Generated by Django 2.2.13 on 2021-01-20 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0017_article_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='access',
            field=models.CharField(choices=[('shared', 'Общий'), ('hidden', 'Скрытый'), ('private', 'Приватный')], default='shared', max_length=15, verbose_name='Доступ'),
        ),
        migrations.AddField(
            model_name='article',
            name='access_list',
            field=models.ManyToManyField(blank=True, related_name='access_articles', to=settings.AUTH_USER_MODEL, verbose_name='Кому доступен файл'),
        ),
    ]
